# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.7.2_1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.7.2_1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/cyril/sbfs

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/cyril/sbfs

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.7.2_1/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.4.3/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/cyril/sbfs/CMakeFiles /Users/cyril/sbfs/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/cyril/sbfs/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sbfs

# Build rule for target.
sbfs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sbfs
.PHONY : sbfs

# fast build rule for target.
sbfs/fast:
	$(MAKE) -f CMakeFiles/sbfs.dir/build.make CMakeFiles/sbfs.dir/build
.PHONY : sbfs/fast

#=============================================================================
# Target rules for targets named SbfsDB

# Build rule for target.
SbfsDB: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SbfsDB
.PHONY : SbfsDB

# fast build rule for target.
SbfsDB/fast:
	$(MAKE) -f CMakeFiles/SbfsDB.dir/build.make CMakeFiles/SbfsDB.dir/build
.PHONY : SbfsDB/fast

#=============================================================================
# Target rules for targets named sbfs_database_test

# Build rule for target.
sbfs_database_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sbfs_database_test
.PHONY : sbfs_database_test

# fast build rule for target.
sbfs_database_test/fast:
	$(MAKE) -f test/CMakeFiles/sbfs_database_test.dir/build.make test/CMakeFiles/sbfs_database_test.dir/build
.PHONY : sbfs_database_test/fast

sbfs.o: sbfs.cc.o

.PHONY : sbfs.o

# target to build an object file
sbfs.cc.o:
	$(MAKE) -f CMakeFiles/sbfs.dir/build.make CMakeFiles/sbfs.dir/sbfs.cc.o
.PHONY : sbfs.cc.o

sbfs.i: sbfs.cc.i

.PHONY : sbfs.i

# target to preprocess a source file
sbfs.cc.i:
	$(MAKE) -f CMakeFiles/sbfs.dir/build.make CMakeFiles/sbfs.dir/sbfs.cc.i
.PHONY : sbfs.cc.i

sbfs.s: sbfs.cc.s

.PHONY : sbfs.s

# target to generate assembly for a file
sbfs.cc.s:
	$(MAKE) -f CMakeFiles/sbfs.dir/build.make CMakeFiles/sbfs.dir/sbfs.cc.s
.PHONY : sbfs.cc.s

sbfs_database.o: sbfs_database.cc.o

.PHONY : sbfs_database.o

# target to build an object file
sbfs_database.cc.o:
	$(MAKE) -f CMakeFiles/SbfsDB.dir/build.make CMakeFiles/SbfsDB.dir/sbfs_database.cc.o
.PHONY : sbfs_database.cc.o

sbfs_database.i: sbfs_database.cc.i

.PHONY : sbfs_database.i

# target to preprocess a source file
sbfs_database.cc.i:
	$(MAKE) -f CMakeFiles/SbfsDB.dir/build.make CMakeFiles/SbfsDB.dir/sbfs_database.cc.i
.PHONY : sbfs_database.cc.i

sbfs_database.s: sbfs_database.cc.s

.PHONY : sbfs_database.s

# target to generate assembly for a file
sbfs_database.cc.s:
	$(MAKE) -f CMakeFiles/SbfsDB.dir/build.make CMakeFiles/SbfsDB.dir/sbfs_database.cc.s
.PHONY : sbfs_database.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... sbfs"
	@echo "... SbfsDB"
	@echo "... sbfs_database_test"
	@echo "... sbfs.o"
	@echo "... sbfs.i"
	@echo "... sbfs.s"
	@echo "... sbfs_database.o"
	@echo "... sbfs_database.i"
	@echo "... sbfs_database.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

